# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install other Python tools
        run: |
          pip install flake8 mypy pytest pytest-custom_exit_code black

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 --count --select=E9,F63,F7,F82 --show-source --statistics src
          # treat all others errors as warnings, and don't fail the check.
          flake8 --count --max-line-length=88 --statistics src

      - name: Check types with mypy, if present
        run: mypy

      - name: Test with pytest, if present
        run: pytest --suppress-no-test-exit-code

      - name: Check formatting with black
        run: black --check src
